#!/usr/bin/env python
"""Featurize a dataset using avocado"""

import argparse

import avocado


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'dataset',
        help='Name of the dataset to featurize.'
    )
    parser.add_argument(
        '--chunk',
        type=int,
        default=None,
        help='If set, process the dataset by chunks. This sets the chunk '
        'number of the dataset to use.',
    )
    parser.add_argument(
        '--num_chunks',
        type=int,
        default=100,
        help='If chunk is set, this is the total number of chunks to use for '
        'processing the dataset. (default: %(default)s)',
    )
    parser.add_argument(
        '--tag',
        default=avocado.settings['features_tag'],
        help='The tag to use for these features. The default is set in '
        'avocado_settings.json. (default: %(default)s',
    )

    args = parser.parse_args()

    # Load the reference dataset
    print("Loading dataset...")
    dataset = avocado.load(
        args.dataset,
        chunk=args.chunk,
        num_chunks=args.num_chunks,
    )

    # Load the featurizer. For now, we only have the PLAsTiCC featurizer
    # although this could be an option in the future.
    print("Loading featurizer...")
    featurizer = avocado.plasticc.PlasticcFeaturizer()

    # Featurize the dataset
    print("Featurizing the dataset...")
    dataset.extract_raw_features(featurizer)

    # Save the features.
    print("Saving the features...")
    dataset.write_raw_features(tag=args.tag)

    print("Done!")
