#!/usr/bin/env python
"""Train a classifier using avocado.

TODO: Add options for weights, classifier kind, featurizer, etc.
"""

import argparse

import avocado


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'dataset',
        help='Name of the dataset to train on.'
    )
    parser.add_argument(
        'classifier',
        help='Name of the classifier to produce.'
    )

    args = parser.parse_args()

    # Load the dataset
    print("Loading dataset '%s'..." % args.dataset)
    dataset = avocado.load(args.dataset, metadata_only=True)

    # Load the dataset raw features
    print("Loading raw features...")
    dataset.load_raw_features()

    # Train the classifier
    print("Training classifier '%s'..." % args.classifier)
    classifier = avocado.LightGBMClassifier(
        args.classifier,
        avocado.plasticc.PlasticcFeaturizer(),
        avocado.plasticc.plasticc_kaggle_weights
    )
    classifier.train(dataset)

    # Save the classifier
    print("Saving the classifier...")
    classifier.write(overwrite=True)

    print("Done!")
